### ISSUE TITLE
[Deprecated]  Buffer(). Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by dlh2** [schnittstabil/char-buffer#4]
Hi, in the wholecode there is new Buffer() instead of Buffer.from().

Could you please change it?

Thanks

**Comment by dlh2** [comment]
Hi, again I see that you've fixed the issue, but may I ask to update it for npm package?

I'm using "https://github.com/schnittstabil/caesar-salad".

Thanks

**Comment by schnittstabil** [comment]
Sorry for the delay. I've published `v2.0.0`.
